### ISSUE TITLE
Blinds do not update - Connexoon - Too many retries

### ISSUE THREAD

**Issue by Abidos14** [MadPatrick/somfy#46]
Hello,

I made a git pull on the wrong folder and updated the Somfy plugin to 4.2.14
Since then, blinds do not udpdate any more and I get an error in domoticz.
Commands do work normally. 

Everything worked perfectly untill yesterday morning (included).
However, Somfy's servers experienced some trouble these last hours and Somfy's boxes where updated.
It nevertheless seems back to normal now.

Plugin was stopped this morning during roughly 1 hour and restarted, with same error still there.
Plugin stopped again for 4 hours and restated. Problem still there...

**Box**
Connexoon
Web version
Refresh intervall 10 mn.

**Domoticz**
Version: 2022.2
Build Hash: eea9db734
RPI
Raspbian Buster

Domoticz error
 2023-01-19 16:36:14.774 Error: Volets roulants: Call to function 'onStart' failed, exception details:
2023-01-19 16:36:14.782 Error: Volets roulants: Traceback (most recent call last):
2023-01-19 16:36:14.782 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 575, in onStart
2023-01-19 16:36:14.782 Error: Volets roulants: _plugin.onStart()
2023-01-19 16:36:14.782 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/plugin.py", line 176, in onStart
2023-01-19 16:36:14.782 Error: Volets roulants: filtered_devices = self.tahoma.get_devices()
2023-01-19 16:36:14.782 Error: Volets roulants: File "/home/pi/domoticz/plugins/somfy/tahoma.py", line 138, in get_devices
2023-01-19 16:36:14.782 Error: Volets roulants: raise exceptions.TooManyRetries
2023-01-19 16:36:14.782 Error: Volets roulants: exceptions.TooManyRetries: Failed to call Tahoma/Somfy API (too many retries) 

Plugin logs
[somfy.log](https://github.com/MadPatrick/somfy/files/10458246/somfy.log)

**Comment by jcbraem** [comment]
Hello,
Same issue for me with same parameters except for refresh delay equal 5 minutes. Stop during one night and directly this error.
Strange because this error is not recurring all time.

[somfy.log](https://github.com/MadPatrick/somfy/files/10463161/somfy.log)


> 2023-01-20 05:20:13.571 Status: Connexoon Somfy Vélux: Initialized version 4.2.14, author 'MadPatrick'
2023-01-20 05:20:13.628 Status: Connexoon Somfy Vélux: Location does not exist, logging to default location
2023-01-20 05:20:13.628 Status: Connexoon Somfy Vélux: Starting Tahoma blind plugin, logging to file somfy.log
2023-01-20 05:20:51.353 Error: Connexoon Somfy Vélux: Call to function 'onStart' failed, exception details:
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 575, in onStart
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: _plugin.onStart()
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 176, in onStart
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: filtered_devices = self.tahoma.get_devices()
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 138, in get_devices
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: raise exceptions.TooManyRetries
2023-01-20 05:20:51.356 Error: Connexoon Somfy Vélux: exceptions.TooManyRetries: Failed to call Tahoma/Somfy API (too many retries)

**Comment by jcbraem** [comment]
Other case :

> 2023-01-20 07:35:38.534 Error: Connexoon Somfy Vélux: Failed to get events: Failed to call Tahoma/Somfy API (too many retries)
2023-01-20 07:36:14.127 Error: Connexoon Somfy Vélux hardware (58) thread seems to have ended unexpectedly
2023-01-20 07:36:15.943 Error: Connexoon Somfy Vélux: Failed to get events: Failed to call Tahoma/Somfy API (too many retries)

[somfy.log](https://github.com/MadPatrick/somfy/files/10464188/somfy.log)

**Comment by JanJaapKo** [comment]
Hi,

This seems to be a problem on the side of the server. I don't think there is much I can do about it (in previous updates I already made sure to handle the time outs and connection disruptions elegantly, as in not creating enormous error logs).

To verify that is is indeed a server issue it would be nice if you could try to connect to tahoma server via your mobile app and see if that still has a connection (but may be difficult to time....)

**Comment by Tatroxitum** [comment]
Hi,
There was an update of their servers tuesday,
I still have problems since
So for me it's on their side, just wait and see

Maintenance des serveurs

Une maintenance des serveurs est prévue mardi 17 janvier, entre 10h et 12h.
Pendant cette maintenance, vos équipements (réglage et pilotage) ne
pourront pas être modifiés et seront indisponibles.
Vos scénarios et votre fonction « ma sécurité » restent disponibles (pour
TaHoma V2 Premium).
Cependant, aucune modification ne sera possible jusqu’à 12h.
Il est également possible que vous n'ayez pas accès à votre interface
pendant quelques minutes.

Des perturbations peuvent être constatées jusqu'au soir.

**Comment by MadPatrick** [comment]
For the non-french speaking people:

```
Server maintenance

A maintenance of the servers is scheduled on Tuesday, January 17th, between 10am and 12pm.
During this maintenance, your equipment (setting and control) will not be able to be
cannot be modified and will be unavailable.
Your scenarios and your "my security" function will remain available (for
TaHoma V2 Premium).
However, no modification will be possible until 12:00.
It is also possible that you will not have access to your interface
for a few minutes.

Disruptions may occur until the evening.
```

**Comment by Doudou14** [comment]
There was a problem with the servers late Wednesday afternoon. But once the problem was solved everything worked again.
On the web interface, I was offered to update the box and since then, the script no longer works
The mobile application works normally.

**Comment by jcbraem** [comment]
Very strange but when I restart the plugin after on wait time, I have this error !
Several tests with the same issue.

[somfy.log](https://github.com/MadPatrick/somfy/files/10464940/somfy.log)

>2023-01-20 10:15:31.357 Status: Connexoon Somfy Vélux: Initialized version 4.2.14, author 'MadPatrick'
2023-01-20 10:15:31.358 Status: Connexoon Somfy Vélux: Location does not exist, logging to default location
2023-01-20 10:15:31.358 Status: Connexoon Somfy Vélux: Starting Tahoma blind plugin, logging to file somfy.log
2023-01-20 10:16:10.210 Error: Connexoon Somfy Vélux: Call to function 'onStart' failed, exception details:
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: Traceback (most recent call last):
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 575, in onStart
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: _plugin.onStart()
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/plugin.py", line 176, in onStart
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: filtered_devices = self.tahoma.get_devices()
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: File "/home/jcb/domoticz/plugins/somfy/tahoma.py", line 138, in get_devices
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: raise exceptions.TooManyRetries
2023-01-20 10:16:10.211 Error: Connexoon Somfy Vélux: exceptions.TooManyRetries: Failed to call Tahoma/Somfy API (too many retries)

**Comment by jcbraem** [comment]
I have try to connect with mobil App and I have one update pending.
Now is in progress ... I hope one better Connexoon box ...

**Comment by jcbraem** [comment]
No change after update and restart plugin. Always directly the error about 'too many retries'

And mostly : no update of widget with reality in Domoticz. Level are OK and react in mobil App.
The physical equipment is reacted when I change the level in Domoticz but reset to open in widget !

**Comment by MadPatrick** [comment]
can you try to disable the plugin for a longer period so it does not try to make a connection with Somfy
Maybe will this stop the "Many retries/connection" problem.

**Comment by JanJaapKo** [comment]
OK, found it: I forgot to jump out of this 4 times retrying loop when it succeeded..... should be solved in version 16, can you please check?

**Comment by Doudou14** [comment]
I still have the same error on local access
But if I put in Web mode, it is Ok.
Thank you for your quick intervention

**Comment by Abidos14** [comment]
Yes, it looks OK now.
Thanks a lot Jan Jaap!!!

**Comment by Tatroxitum** [comment]
I've made an update of the somfy domoticz plugin since the update of the somfy servers.
(Connexoon)
At plugin startup the devices are correctly updated

but the polling do not update the devices

Polling unit in 2 heartbeats.
2023-01-20 22:22:36,098 - DEBUG    - plugin.py          - Polling unit in 1 heartbeats.
2023-01-20 22:22:37,051 - DEBUG    - plugin.py          - Poll unit
2023-01-20 22:22:37,053 - DEBUG    - tahoma.py          - checking logged in status: self.__logged_in = True and self.__expiry_date (2023-01-20 22:14:07.774452) >= datetime.datetime.now() = False
2023-01-20 22:22:37,055 - DEBUG    - tahoma.py          - Asking tahoma server if we're good to go
2023-01-20 22:22:37,072 - DEBUG    - connectionpool.py  - Starting new HTTPS connection (1): tahomalink.com:443
2023-01-20 22:22:37,216 - DEBUG    - connectionpool.py  - https://tahomalink.com:443 "GET /enduser-mobile-web/enduserAPI/authenticated HTTP/1.1" 200 None
2023-01-20 22:22:37,227 - DEBUG    - tahoma.py          - get login status response: status '200' response body: '{'authenticated': False}'
2023-01-20 22:22:37,228 - DEBUG    - tahoma.py          - checking logged in status: self.__logged_in = False and self.__expiry_date (2023-01-20 22:14:07.774452) >= datetime.datetime.now() = False
2023-01-20 22:22:37,229 - DEBUG    - plugin.py          - attempting to poll web version but not logged in
2023-01-20 22:22:37,236 - DEBUG    - connectionpool.py  - Starting new HTTPS connection (1): tahomalink.com:443
2023-01-20 22:22:37,872 - DEBUG    - connectionpool.py  - https://tahomalink.com:443 "POST /enduser-mobile-web/enduserAPI/login HTTP/1.1" 200 None
2023-01-20 22:22:37,883 - DEBUG    - tahoma.py          - Login respone: status_code: '200' reponse body: '{'success': True, 'roles': [{'name': 'ENDUSER'}]}'
2023-01-20 22:22:37,884 - INFO     - tahoma.py          - Tahoma authentication succeeded, login valid until 2023-01-20 22:24:07
2023-01-20 22:22:37,884 - DEBUG    - tahoma.py          - login: cookies: '<RequestsCookieJar[<Cookie JSESSIONID=8CD1B524ABE3013D0665B679EFB93FCC for tahomalink.com/enduser-mobile-web>]>', headers: '{'Date': 'Fri, 20 Jan 2023 21:22:37 GMT', 'Server': 'overkiz', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains, max-age=31536000 ; includeSubDomains', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/json;charset=UTF-8', 'Set-Cookie': 'JSESSIONID=8CD1B524ABE3013D0665B679EFB93FCC; Path=/enduser-mobile-web; Secure; HttpOnly; SameSite=None', 'Keep-Alive': 'timeout=5, max=50', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked'}'
2023-01-20 22:22:38,086 - DEBUG    - plugin.py          - Polling unit in 599 heartbeats.
2023-01-20 22:22:39,090 - DEBUG    - plugin.py          - Polling unit in 598 heartbeats.

=> i've changed the status of the blinds but as you can see no update is seen.

**Comment by jcbraem** [comment]
After this update v16 I have directly the good state retrieve without any errors !
All changes are retrieve and send from/to Domoticz.

Wait a little bit ... but I a very good starting :)

**Comment by JanJaapKo** [comment]
> I still have the same error on local access But if I put in Web mode, it is Ok. Thank you for your quick intervention

@Doudou14 if this still occurs, please create a separate issue for the local mode with the somfy log file included

@Tatroxitum please also submit somfy log file

**Comment by Tatroxitum** [comment]
Here the log file 
[somfy.log](https://github.com/MadPatrick/somfy/files/10473089/somfy.log)
2023-01-20 22:12:38 : start and getting statuses (ok)
2023-01-20 22:15 : approx, change status of the blinds 
2023-01-20 22:22:37 : update doesn't see the changes (and after few hours neither, same log).

Personnally I prefer the local connexion as it works now for connexoon, note sure if the web api is now interesting...

**Comment by JanJaapKo** [comment]
Since all positive reactions on #47, not going to solve this anymore
